### ISSUE TITLE
P2Rank with conservation

### ISSUE THREAD

**Issue by davidhoksza** [bartongroup/LBS-comparison#1]
Hi @JavierSanchez-Utges , 

Impressive and thorough work! The P2Rank conservation tool can be run using a Docker image, which is used within the PrankWeb web server, but should be easily usable separately as detailed [here](https://github.com/cusbg/p2rank-framework/wiki/P2Rank-deploy-with-Docker). ... Just in case you wanted to have this information in the main README.

**Comment by JavierSanchez-Utges** [comment]
Hi, @davidhoksza. Thanks for letting me know. This information has now been added to the README. Cheers!
